language: php
php:
  - 7.2
  - 7.3
  - nightly
branches:
  only:
    - master
    - stable
    - test
before_install:
  - sudo apt update
  - sudo apt install
install:
  - composer install
env:
matrix:
  allow_failures:
    - php: nightly
script: ./vendor/bin/phpunit --configuration ./phpunit.xml